name: doc_widget_builder
description: The code generator to generate the documentation for doc_widget package.
version: 0.1.6
homepage: https://github.com/isacjunior/doc_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.3.0
  build_config: ^0.4.2
  source_gen: ^0.9.6
  analyzer: ^0.39.11
  code_builder: ^3.4.1
  dart_style: ^1.3.6
  doc_widget_annotation: ^0.1.1

dev_dependencies:
  test: ^1.15.3
  source_gen_test: ^0.1.1
  build_runner: ^1.10.1