name: doc_widget_builder
description: The code generator to generate the documentation for doc_widget package.
version: 0.2.9
homepage: https://github.com/isacjunior/doc_widget

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ">=2.3.1 <3.0.0"
  build_config: ">=1.1.0 <3.0.0"
  source_gen: ^1.2.3
  analyzer: ">=4.4.0 <6.0.0"
  code_builder: ">=4.3.0 <6.0.0"
  dart_style: ">=2.2.4 <6.0.0"
  doc_widget_annotation: ^0.2.8

dev_dependencies:
  test: ^1.17.12
  source_gen_test: ^1.0.4
  build_runner: ^2.2.1
