name: doc_widget_builder
description: The code generator to generate the documentation for doc_widget package.
version: 0.2.7
homepage: https://github.com/isacjunior/doc_widget

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ">=2.1.0 <3.0.0"
  build_config: ">=1.0.0 <3.0.0"
  source_gen: ^1.0.3
  analyzer: ">=1.7.1 <3.0.0"
  code_builder: ">=4.1.0 <6.0.0"
  dart_style: ">=2.1.1 <6.0.0"
  doc_widget_annotation: ^0.1.8

dev_dependencies:
  test: ^1.17.12
  source_gen_test: ^1.0.1
  build_runner: ^2.1.2
